from pydantic import BaseModel
from typing import List, Optional
from datetime import datetime
from decimal import Decimal
from ledger_guard.config import MAX_SETTLEMENT_LAG_DAYS, FUZZY_MATCH_THRESHOLD

class ReconJobPolicy(BaseModel):
    """
    Overarching ruleset for a reconciliation batch.
    """
    target_currency: str = "INR"
    max_settlement_lag_days: int = 3
    fuzzy_match_threshold: int = 75
    max_fee_pct: float = 0.03

class FinancialEvent(BaseModel):
    """
    A concrete economic action, aggregating one or more atomic FactLedger rows.
    E.g., SALE, PAYMENT_COLLECTION, BANK_CREDIT
    """
    id: str
    fact_ids: List[int]
    event_type: str
    amount: Decimal
    currency: str
    transaction_date: datetime
    description: str
    transaction_id: str

class ReconEdge(BaseModel):
    """
    Represents a plausible mathematical and contextual match between two events.
    """
    source_event_id: str
    target_event_id: str
    match_score: int # 0-100
    amount_diff: Decimal
    time_delta_days: int
    match_reason: str # 'ECONOMIC_BOUND', 'FUZZY_TOKEN'


class SolverResult(BaseModel):
    """Output of the MILP solver for a single cluster."""
    cluster_id: str
    status: str  # OPTIMAL_UNIQUE, ABSTAIN_TIMEOUT, AMBIGUOUS, INFEASIBLE, OVERSIZED
    matched_pairs: List[dict] = []  # [{source_id, target_id, amount, score, reason}]
    solver_time_ms: float = 0.0
    message: str = ""

class ProposedSolution(BaseModel):
    """
    A unified proposal generated by either Block 3 (MILP Solver) or Block 4 (AI Investigator).
    Submitted to Block 5 for deterministic verification.
    """
    source_event_ids: List[str]
    target_event_id: str
    source_fact_ids: List[int]
    target_fact_ids: List[int]
    allocated_amount: Decimal
    match_reason: str
    cluster_id: str
    solver_status: str # OPTIMAL_UNIQUE or PROVEN_AI_CASE

